---
include:
  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart MKB_L_TB
    artifact-name: MKB_L_MODULE_TB

  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart MKB_L_JS_Enc
    artifact-name: MKB_L_MODULE_JOY

  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart MKB_L_Enc
    artifact-name: MKB_L_MODULE_ENC

  - board: seeeduino_xiao_ble
    shield: MKB_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart

  - board: seeeduino_xiao_ble
    shield: settings_reset
