---
include:
# Unified (step migration target)
  - board: seeeduino_xiao_ble
    shield: MKB_L_Base MKB_L_UNI rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_UNIFIED

  - board: seeeduino_xiao_ble
    shield: MKB_R_Base MKB_R_UNI rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_R_UNIFIED

