manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: te9no
      url-base: https://github.com/te9no
    - name: kot149
      url-base: https://github.com/kot149
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: cormoran
      url-base: https://github.com/cormoran
  projects:
    - name: zmk
      # remote: zmkfirmware
      remote: te9no
      revision: afe241df80b05c3f4e0cc95ada7584d24422a893
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: e6b467792a1dabef8cfa5c9fd26bfefc9c16662b
    - name: zmk-analog-input-driver
      remote: badjeff
      revision: 2684f22ee7e2168d4393f7e63676912210a796fc
    - name: zmk-nice-oled
      remote: te9no
      revision: 537666b5aca8c04276f3d2e9d614eb31c6d5be7e
    - name: zmk-layout-shift
      remote: kot149
      revision: 4d71f7cb743256ac619873dd44f510e9e9562739
    - name: zmk-input-processor-keybind
      remote: te9no
      revision: 10ad463f2e3c7a7dfb4b7cffd6bddd0e9e8b5bae
    - name: zmk-driver-MLX90393
      remote: te9no
      revision: 42297df2ce839556eaee94e5ddcb8494355e1312
    - name: ads1220-zephyr-module
      remote: te9no
      revision: d618d1f3f198fd7e4ca3469da1683644be2d1b9f

    - name: zmk-module-runtime-input-processor
      remote: te9no
      revision: 72387b5212264d26d704dbc43c765f6485470a77
    - name: zmk-module-ble-management
      remote: cormoran
      revision: 57738cc4fc6ba80e82a7ac57741a0339cb186cd4
    - name: zmk-module-settings-rpc
      remote: cormoran
      revision: 083a299dd8d31c275809c5a249b12486be24a7d2
    - name: zmk-feature-cdc-acm-bootloader-trigger
      remote: te9no
      revision: 1850754d269aab9ba73e4639371bfe59a4130e65
    - name: zmk-module-analoginput-rpc
      remote: te9no
      revision: e065461e907fa924c0029e1d4c94cec1d9093e17
    - name: zmk-module-battery-nrf-vddh-oversampling
      remote: te9no
      revision: 59fc126f859d4e7700186c9906e4645379763c34

  self:
    path: config

    
