# USB + BLE (peripheral)
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

# Basic hardware
CONFIG_INPUT=y
CONFIG_PINCTRL=y
CONFIG_I2C=y
CONFIG_I2C_NRFX=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_SENSOR=y

# Logging (USB OK)
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# RGB LED widget (battery peripheral 表示は NG)
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=y
CONFIG_RGBLED_WIDGET_LAYER_COLOR=7

# Thread stack sizes (peripheral)
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=2048
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=2048
CONFIG_INPUT_THREAD_STACK_SIZE=2048
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_STACK_SIZE=2048

# Bluetooth PHY
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# JIS layout shift
CONFIG_LAYOUT_SHIFT_TARGET_JIS=y

# Runtime input processor
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y

# Settings
CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
CONFIG_ZMK_SETTINGS_RPC=y

# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Split relay
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
