CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_INPUT=y

CONFIG_ADC_ADS1220=y
CONFIG_GPIO_ADS1220=y
CONFIG_INPUT_ANALOG_AXIS_HIRES=y
CONFIG_INPUT_ANALOG_AXIS_HIRES_SETTINGS=n
CONFIG_INPUT_ANALOG_AXIS_HIRES_THREAD_STACK_SIZE=3072
CONFIG_MULTITHREADING=y

CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETENTION_BOOT_MODE=y
CONFIG_CDC_ACM_DTE_RATE_CALLBACK_SUPPORT=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_SETTINGS_RPC=n
CONFIG_ZMK_BLE_MANAGEMENT=n
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=n
CONFIG_ZMK_SETTINGS_RPC_STUDIO=n
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=n

CONFIG_ZMK_LOG_LEVEL_INF=y
CONFIG_ADC_LOG_LEVEL_WRN=y
CONFIG_GPIO_LOG_LEVEL_WRN=y
CONFIG_INPUT_LOG_LEVEL_INF=y
CONFIG_LOG_BACKEND_UART_BUFFER_SIZE=128
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_BT_RX_STACK_SIZE=1536
CONFIG_INPUT_THREAD_STACK_SIZE=1536
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=1536
