# Enable MLX90393 driver
CONFIG_SPI=y
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_INPUT_MLX90393=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
# Turn on mouse key
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

CONFIG_USB_DEVICE_HID=y
CONFIG_USB_HID_DEVICE_COUNT=2
CONFIG_ZMK_HID_JOYSTICK=y
CONFIG_ZMK_HID_JOYSTICK_LOG_LEVEL_DBG=y
