name: Build ZMK firmware

on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - boards/**
      - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  upload-firmware:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Get branch name
        id: branch-name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Prepare firmware directory
        run: |
          mkdir -p firmware/${{ steps.branch-name.outputs.branch }}
          rm -rf firmware/${{ steps.branch-name.outputs.branch }}/*

      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware/${{ steps.branch-name.outputs.branch }}

      - name: Commit updated images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'firmware/**/*'
          commit_message: 'Update firmware files for branch ${{ steps.branch-name.outputs.branch }}'
          commit_options: '--no-verify'
          push_options: '--no-verify'

      - name: Artifact upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'firmware'
          path: 'firmware/${{ steps.branch-name.outputs.branch }}/*'
