name: Build ZMK firmware

on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - boards/**
      - build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install west + deps
        run: |
          pip install west
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake gcc-arm-none-eabi

      - name: West init
        run: west init -l .

      - name: West update
        run: west update

      - name: Build firmware
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble -- \
            -DSHIELD="MKB_L_Base MKB_L_JOY rgbled_adapter nice_oled"
